<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-18 06:29
=======
# Generated by Django 3.2.5 on 2021-07-18 06:21
>>>>>>> f90ae96b23739b098e4cce3b96f8411987e59d93

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='leaderboard',
=======
            name='Leaderboard',
>>>>>>> f90ae96b23739b098e4cce3b96f8411987e59d93
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=10)),
                ('task_title', models.CharField(max_length=1000)),
                ('task_des', models.CharField(max_length=1000)),
            ],
        ),
    ]
